<?php
// -------------------------------------------------------------------------------------------------
// Seiteninhalt Schwedisch
// -------------------------------------------------------------------------------------------------

// Header
$loc_etymos_woerterbuch = 'Etymos-Ordbok - flerspråkig och flera riktningar';
// $loc_description = '';
$loc_keywords = 'språk, översättning, ordbok, grammatik, böjning, deklination, konjugation, fonetik, uttal';

// Wörterbuchsprachen in spezifischer Reihenfolge
$dictlanguage = array('sqi', 'ara', 'bos', 'bul', 'dan', 'eng', 'est', 'fin', 'fra', 'ell', 'gle', 'isl', 'ita', 'cat', 'hrv', 'lav', 'lit', 'ltz', 'mkd', 'nld', 'nor', 'pol', 'por', 'ron', 'rus', 'srp', 'slk', 'slv', 'spa', 'swe', 'ces', 'tur', 'deu', 'ukr', 'hun', 'bel');

// Sprachnamen
$language = array(
    'ara' => 'Arabiska',
    'bel' => 'Vitryska',
    'bos' => 'Bosniska',
    'bul' => 'Bulgariska',
    'cat' => 'Katalanska',
    'ces' => 'Tjeckiska',
    'dan' => 'Danska',
    'deu' => 'Tyska',
    'ell' => 'Grekiska',
    'eng' => 'Engelska',
    'est' => 'Estniska',
    'fin' => 'Finska',
    'fra' => 'Franska',
    'gle' => 'Irländska',
    'hrv' => 'Kroatiska',
    'hun' => 'Ungerska',
    'isl' => 'Isländska',
    'ita' => 'Italienska',
    'lav' => 'Lettiska',
    'lit' => 'Litauiska',
    'ltz' => 'Luxemburgiska',
    'mkd' => 'Makedonska',
    'nld' => 'Nederländska',
    'nor' => 'Norska',
    'pol' => 'Polska',
    'por' => 'Portugisiska',
    'ron' => 'Rumänska',
    'rus' => 'Ryska',
    'slk' => 'Slovakiska',
    'slv' => 'Slovenska',
    'spa' => 'Spanska',
    'sqi' => 'Albanska',
    'srp' => 'Serbiska',
    'swe' => 'Svenska',
    'tur' => 'Turkiska',
    'ukr' => 'Ukrainska',
    'fas' => 'Persiska',
    'fry' => 'Frisiska',
    'hye' => 'Armeniska',
    'goh' => 'Fornhögtyska',
    'lat' => 'Latinska',
    'pie' => 'Urindoeuropeiska',
    'pgm' => 'Urgermanska',
    'akk' => 'Akkadiska',
    'grc' => 'Klassisk grekiska',
    'pfi' => 'Urfinska',
);

// Tooltips für Kategorien
// $loc_verwendungsbereich = '';
// $loc_stilebene = '';
// $loc_fachgebiet = '';
// $loc_region = '';
$tooltip[1] = 'ålderdomligt';
// $tooltip[2] = 'klassisch, altliterarisch';
$tooltip[3] = 'talspråklig';
// $tooltip[4] = 'dialektal, mundartlich';
$tooltip[5] = 'familjär';
// $tooltip[6] = 'falsial, fälschlich';
// $tooltip[7] = 'figurativ, übertragen';
// $tooltip[8] = 'infantil, kindersprachlich, babysprachlich';
// $tooltip[9] = 'jargonal, milieusprachlich';
// $tooltip[10] = 'literarisch, literatursprachlich';
// $tooltip[11] = 'neologistisch, kunstsprachlich';
$tooltip[12] = 'föråldrat';
// $tooltip[13] = 'obszön, unanständig';
// $tooltip[14] = 'poetisch, lyrisch';
// $tooltip[15] = 'raritätisch, ungebräuchlich';
// $tooltip[16] = 'regional, gebietsweise';
// $tooltip[17] = 'skribal, schriftsprachlich';
// $tooltip[18] = 'slang, straßensprachlich';
// $tooltip[19] = 'gehoben, bildungssprachlich';
// $tooltip[20] = 'tabuisiert, geächtet';
// $tooltip[21] = 'vulgär, derb';
// $tooltip[32] = 'kalmierativ, beschwichtigend, beruhigend';
// $tooltip[33] = 'kommandierend, befehlend';
// $tooltip[34] = 'dysphemisch, herabsetzend, verfälschend negativ';
// $tooltip[35] = 'emphatisch, leidenschaftlich, nachdrücklich';
// $tooltip[36] = 'euphemisch, beschönigend, verfälschend positiv';
// $tooltip[37] = 'euphorisch, begeistert';
// $tooltip[38] = 'exklematorisch, ausrufend';
// $tooltip[39] = 'formell, förmlich';
// $tooltip[40] = 'humorvoll, scherzhaft';
// $tooltip[41] = 'insultiv, beleidigend';
// $tooltip[42] = 'ironisch, umkehrend';
// $tooltip[43] = 'meliorativ, aufwertend, lobend';
// $tooltip[44] = 'negativ, verneinend';
// $tooltip[45] = 'pejorativ, abwertend, verächtlich';
// $tooltip[46] = 'positiv, bejahend';
// $tooltip[47] = 'provokativ, hetzerisch';
// $tooltip[48] = 'sarkastisch, verhöhnend, verspottend';
// $tooltip[49] = 'zynisch, verletzend, missachtend';
// $tooltip[50] = 'inquestiv, fragend';
// $tooltip[51] = 'surpressiv, überrascht';
// $tooltip[64] = 'Wissenschaft';
// $tooltip[65] = 'Pojonik, Philosophie';
// $tooltip[66] = 'Posonik, Mathematik';
// $tooltip[67] = 'Fysonik, Physik';
// $tooltip[68] = 'Vivonik, Biologie';
// $tooltip[69] = 'Sykonik, Psychologie';
// $tooltip[70] = 'Komonik, Soziologie';
// $tooltip[71] = 'Hylonik, Chemie';
// $tooltip[72] = 'Gejonik, Physiogeografie, Geologie, Meteorologie';
// $tooltip[73] = 'Kelonik, Astronomie';
// $tooltip[74] = 'Vironik, Virologie';
// $tooltip[75] = 'Litonik, Bakteriologie';
// $tooltip[76] = 'Zojonik, Zoologie';
// $tooltip[77] = 'Botonik, Botanik';
// $tooltip[78] = 'Mykonik, Mykologie';
// $tooltip[79] = 'Domonik, Ökologie';
// $tooltip[80] = 'Fabonik, Historik, Geschichte, Archäologie';
// $tooltip[81] = 'Kolonik, Humangeografie';
// $tooltip[82] = 'Voxonik, Linguistik, Sprachwissenschaft';
// $tooltip[83] = 'Mosonik, Kulturwissenschaft';
// $tooltip[128] = 'Technik, Ingenieurwesen';
// $tooltip[129] = 'Ökonomie, Wirtschaft, Management';
// $tooltip[130] = 'Bildungswesen, Ausbildung, Erziehung, Pädagogik';
// $tooltip[131] = 'Finanzen, Banken, Versicherungen, Immobilien';
// $tooltip[132] = 'Handel, Lagerwirtschaft';
// $tooltip[133] = 'Transportwesen, Landtransportmittel';
// $tooltip[134] = 'Marine, Seefahrt, Schifffahrt';
$tooltip[135] = 'luftfart';
// $tooltip[136] = 'Astronautik, Raumfahrt';
// $tooltip[137] = 'Postwesen, Nachrichtenwesen';
// $tooltip[138] = 'Telekommunikation, Fernsehtechnik, Radiotechnik';
// $tooltip[139] = 'Informatik, Informationstechnik, Computer, Kybernetik';
// $tooltip[140] = 'Agronomie, Landwirtschaft, Forstwirtschaft, Gartenbau, Fischwirtschaft, Jagd';
// $tooltip[141] = 'Bergbau, Rohstoffextraktion';
// $tooltip[142] = 'Energie-, Wasserversorgung, Abwasser-, Müllentsorgung';
$tooltip[143] = 'metallurgi';
// $tooltip[144] = 'Materialwissenschaft, Werkstoffwissenschaft';
// $tooltip[145] = 'Bauwesen, Architektur (Technik), Stadtplanung';
// $tooltip[146] = 'Maschinenbau, Gerätebau, Möbel';
// $tooltip[147] = 'Elektrotechnik, Elektrik, Elektronik';
$tooltip[148] = 'mode';
// $tooltip[149] = 'Kosmetik, Körperpflege, Hygiene';
// $tooltip[150] = 'Typografie, Buchdruck, Zeitungswesen, Layout';
// $tooltip[151] = 'Fotografie, Lichttechnik';
// $tooltip[152] = 'Journalistik, Medien';
// $tooltip[153] = 'Tourismus, Freizeitwirtschaft';
// $tooltip[176] = 'Medizin, Humanmedizin';
// $tooltip[177] = 'Veterinärmedizin';
// $tooltip[178] = 'Anatomie';
// $tooltip[179] = 'Pharmazie, Pharmazeutik';
// $tooltip[184] = 'Administration, Verwaltung, Amtssprache';
// $tooltip[185] = 'Politik, Politologie, Staat, Regierung, Parlament';
// $tooltip[186] = 'Jura, Recht, Justiz';
// $tooltip[187] = 'Militär, Polizei, Geheimdienst, Waffen';
// $tooltip[192] = 'Grafik, Malerei, Zeichnen, Gravur, Fotokunst';
// $tooltip[193] = 'Skulpturen, Plastiken';
// $tooltip[194] = 'Architektur, Baukunst, Landgestaltung';
// $tooltip[195] = 'Objektdesign, Gebrauchsgegenstandgestaltung';
// $tooltip[196] = 'Kunsthandwerk';
// $tooltip[197] = 'Gastronomie, Kochkunst';
// $tooltip[198] = 'Belletristik, Literatur, Schriftstellerei';
// $tooltip[199] = 'Lyrik, Poesie, Dichtung';
// $tooltip[200] = 'Theater, Schauspiel';
// $tooltip[201] = 'Audiokunst, Hörspielkunst';
// $tooltip[202] = 'Filmkunst, Videokunst';
// $tooltip[203] = 'Komposition, Musik';
// $tooltip[204] = 'Choreografie, Tanz';
// $tooltip[205] = 'Entertainment, Unterhaltung';
// $tooltip[208] = 'Athletik, Sport';
// $tooltip[209] = 'Spiele, Gaming, Spielzeug';
// $tooltip[210] = 'Sammeln, Philatelie, Numismatik';
// $tooltip[224] = 'Religion, Kirche, Theologie';
// $tooltip[225] = 'Esoterik, Pseudoreligion';
// $tooltip[226] = 'Mythologie';
// $tooltip[227] = 'Heraldik';
// $tooltip[256] = 'Hochsprache formal, nicht gebräuchlich';
// $tooltip[257] = 'Nord-';
// $tooltip[258] = 'Ost-';
// $tooltip[259] = 'Süd-';
// $tooltip[260] = 'West-';
// $tooltip[261] = 'Zentral-';
// $tooltip[264] = 'Niederlande';
// $tooltip[265] = 'Flandern (Belgien)';
// $tooltip[268] = 'Schweden';
// $tooltip[269] = 'Finnland';
// $tooltip[272] = 'Portugal';
// $tooltip[273] = 'Brasilien';
// $tooltip[276] = 'Rumänien';
// $tooltip[277] = 'Moldawien';
// $tooltip[280] = 'Andorra und Valencia';
// $tooltip[281] = 'Katalonien';
// $tooltip[284] = 'Böhmen';
// $tooltip[285] = 'Mähren';
$tooltip[320] = 'Tyskland';
// $tooltip[321] = 'Österreich';
// $tooltip[322] = 'Schweiz';
// $tooltip[328] = 'Serbien';
// $tooltip[329] = 'Kroatien';
// $tooltip[330] = 'Bosnien';
// $tooltip[331] = 'Herzegowina';
// $tooltip[332] = 'Montenegro';
// $tooltip[333] = 'Dalmatien';
// $tooltip[384] = 'Ägypten';
// $tooltip[385] = 'Syrien';
// $tooltip[416] = 'Großbritannien';
// $tooltip[417] = 'Amerika';
// $tooltip[418] = 'Irland';
// $tooltip[419] = 'Kanada';
// $tooltip[420] = 'Australien';
// $tooltip[421] = 'Neuseeland';
// $tooltip[422] = 'Indien';
// $tooltip[423] = 'Südafrika';
// $tooltip[424] = 'England';
// $tooltip[425] = 'Schottland';
// $tooltip[448] = 'Frankreich';
// $tooltip[449] = 'Kanada (Quebec)';
// $tooltip[480] = 'Spanien';
// $tooltip[481] = 'Latinika';
// $tooltip['adj'] = 'Adjektiv, Eigenschaftswort';
// $tooltip['adv'] = 'Adverb, Umstandswort';
// $tooltip['art'] = 'Artikel, Begleiter';
// $tooltip['int'] = 'Interjektion, Empfindungswort';
// $tooltip['con'] = 'Konjunktion, Bindewort';
// $tooltip['pro'] = 'Pronomen, Fürwort';
// $tooltip['s'] = 'Substantiv, Hauptwort';
// $tooltip['v'] = 'Verb, Tätigkeitswort';
// $tooltip['cntr'] = 'Kontraktion, Zusammenziehung';
// $tooltip['abbr'] = 'Abbreviation, Abkürzung';
// $tooltip['acro'] = 'Akronym, Initialwort oder Silbenwort';
// $tooltip['brax'] = 'Brachonym, Kurzwort';
// $tooltip['brad'] = 'Bradonym, Vollform';
// $tooltip['part'] = 'Partikel, Verhältnisbeiwort';
// $tooltip['prep'] = 'Präposition, Verhältnisvorwort';
// $tooltip['post'] = 'Postposition, Verhältnisnachwort';
// $tooltip['circ'] = 'Zirkumposition, Verhältnisumwort';
// $tooltip['affx'] = 'Affix, Hinzufügung';
// $tooltip['prfx'] = 'Präfix, vorangestellte Hinzufügung';
// $tooltip['sufx'] = 'Suffix, nachgestellte Hinzufügung';
// $tooltip['cifx'] = 'Zirkumfix, vor- und nachgestellte Hinzufügung';
// $tooltip['infx'] = 'Infix, Einfügung in den Stamm';
// $tooltip['itfx'] = 'Interfix, Einfügung zwischen Teilwörtern';
// $tooltip['cnfx'] = 'Konfix, nur als Hinzufügung existierendes Wort';
// $tooltip['mdfx'] = 'Modifix, Modifikator in einem Kompositum';
// $tooltip['pos'] = 'Positv, Grundform als Ausdruck der Tatsache';
// $tooltip['com'] = 'Komparativ, höherer Grad im Vergleich mit einem anderen';
// $tooltip['ela'] = 'Elativ, sehr hoher Grad im Vergleich mit Durchschnitt';
// $tooltip['sup'] = 'Superlativ, höchster Grad im Vergleich mit allen anderen';
// $tooltip['exc'] = 'Exzessiv, überhöhter Grad im Vergleich mit Optimum';
// $tooltip['ass'] = 'Assoziativ, mit Gelenkartikel';
// $tooltip['def'] = 'definit, bestimmt';
// $tooltip['dem'] = 'demonstativ, hinweisend';
// $tooltip['det'] = 'determinativ, bestimmend';
// $tooltip['ind'] = 'indefinit, unbestimmt';
// $tooltip['int'] = 'interrogativ, fragend';
// $tooltip['per'] = 'personal, personanzeigend';
// $tooltip['pos'] = 'possessiv, besitzanzeigend';
// $tooltip['rec'] = 'reziprok, wechselseitig';
// $tooltip['ref'] = 'reflexiv, rückbezüglich';
// $tooltip['rel'] = 'relativ, bezüglich';
// $tooltip['si'] = 'Substantiv: Infinitiv, Tätigkeitshauptwort';
// $tooltip['sv'] = 'Substantiv: Verbalnomen Gerundium, Ausführungshauptwort';
// $tooltip['ss'] = 'Substantiv: Singularetantum, Einzahlwort';
// $tooltip['sp'] = 'Substantiv: Pluraletantum, Mehrzahlwort';
// $tooltip['sn'] = 'Substantiv: Proprialnomen, Eigenname';
// $tooltip['ssn'] = 'Substantiv: Proprialnomen als Singularetantum, Eigenname als Einzahlwort';
// $tooltip['ssp'] = 'Substantiv: Proprialnomen als Pluraletantum, Eigenname als Mehrzahlwort';
// $tooltip['m'] = 'maskulinum, männlich';
// $tooltip['f'] = 'femininum, weiblich';
// $tooltip['n'] = 'neutrum, sächlich';
// $tooltip['a'] = 'animativum, belebt';
// $tooltip['i'] = 'inanimativum, unbelebt';
// $tooltip['u'] = 'utrum, doppelgeschlechtlich';
// $tooltip['va'] = 'auxiliares Verb, Hilfsverb';
// $tooltip['vi'] = 'intransitives Verb, ohne Objekte und zwingende Erweiterungen';
// $tooltip['vis'] = 'intransitives Verb, mit zwingender Anfügung eines stativen Objekts';
// $tooltip['via'] = 'intransitives Verb, mit zwingender Anfügung eines Adverbials';
// $tooltip['vip'] = 'intransitives Verb, mit zwingender Anfügung eines präpositiven Objekts';
// $tooltip['vt'] = 'transitives Verb, mit direktem Objekt';
// $tooltip['vts'] = 'transitives Verb, mit direktem Objekt und zwingender Anfügung eines stativen Objekts';
// $tooltip['vm'] = 'ministratives Verb, mit indirektem Objekt';
// $tooltip['vd'] = 'ditransitives Verb, mit direktem und indirektem Objekt';
// $tooltip['vr'] = 'reflexives Verb, mit direktem Objekt identisch zum Subjekt';
// $tooltip['vrp'] = 'reflexives Verb, mit direktem Objekt identisch zum Subjekt und zwingender Anfügung eines präpositiven Objekts';
// $tooltip['vu'] = 'uniteratives Verb, mit indirektem Objekt identisch zum Subjekt';
// $tooltip['vc'] = 'konsekratives Verb, mit direktem Objekt identisch zum Subjekt und mit indirektem Objekt';
// $tooltip['vo'] = 'okkupatives Verb, mit direktem Objekt und mit indirektem Objekt identisch zum Subjekt';
// $tooltip['num'] = 'Numeral, Zahlwort';
// $tooltip['card'] = 'kardinal, eine Grundzahl angebend (eins)';
// $tooltip['coll'] = 'kollektiv, eine Sammelmenge angebend (Dutzend)';
// $tooltip['diff'] = 'diffus, eine unbestimmte Menge angebend (viel)';
// $tooltip['dist'] = 'distinktiv, eine Unterscheidung angebend (zweierlei)';
// $tooltip['frac'] = 'fraktional, einen Bruchteil angebend (halb)';
// $tooltip['iter'] = 'iterativ, eine Wiederholung angebend (einmal)';
// $tooltip['mult'] = 'multiplikativ, eine Vervielfältigung angebend (einfach)';
// $tooltip['ordi'] = 'ordinal, die Ordnung angebend (erstens)';
// $tooltip['soci'] = 'soziativ, die Gesellschaft angebend (zu zweit)';
// $tooltip['succ'] = 'sukzessiv, die Abfolge angebend (erstmals)';
// $tooltip['attr'] = 'attributiv, als Teil des Attributs';
// $tooltip['pred'] = 'prädikativ, als Teil des Prädikats';
// $tooltip['adve'] = 'adversativ, entgegensetzend (aber)';
// $tooltip['caus'] = 'kausal, Ursache oder Grund angebend (wegen)';
// $tooltip['conc'] = 'konzessiv, einräumend (obwohl)';
// $tooltip['cond'] = 'konditional, Bedingung angebend (falls)';
// $tooltip['cons'] = 'konsekutiv, Reihenfolge angebend (nach)';
// $tooltip['copu'] = 'kopulativ, anfügend (und)';
// $tooltip['disj'] = 'disjunktiv, alternativ (oder)';
// $tooltip['fina'] = 'final, Zweck angebend (zwecks)';
// $tooltip['grad'] = 'graduell, konkretisierend (circa)';
// $tooltip['inst'] = 'instrumental, Mittel angebend (mittels)';
// $tooltip['inte'] = 'intensional, Absicht angebend (weil)';
// $tooltip['loca'] = 'lokal, örtlich (neben)';
// $tooltip['moda'] = 'modal, Art und Weise angebend (so)';
// $tooltip['orig'] = 'original, Quelle angebend (von)';
// $tooltip['part'] = 'partiell, anteilig (teils)';
// $tooltip['prop'] = 'propertär, Zugehörigkeit angebend (von)';
// $tooltip['refe'] = 'referent, Bezug angebend (betreffs)';
// $tooltip['rest'] = 'restriktiv, beschränkend (nur)';
// $tooltip['subs'] = 'substitutiv, ersetzend (anstatt)';
// $tooltip['temp'] = 'temporal, zeitlich (bevor)';
// $tooltip['them'] = 'themativ, Thema angebend (über)';
// $tooltip['univ'] = 'universell, Subjekt oder Objekt angebend (man)';
// $tooltip['abs'] = 'absolut, unbezüglich';
// $tooltip['arb'] = 'arbiträr, beliebig';
// $tooltip['dir'] = 'direktional, richtungsbestimmend';
// $tooltip['sg'] = 'Singular, Einzahl';
// $tooltip['du'] = 'Dual, Zweizahl';
// $tooltip['pa'] = 'Paukal, Kleinzahl';
// $tooltip['pl'] = 'Plural, Mehrzahl';
// $tooltip['nom'] = 'Nominativ, Subjekt wer?';
// $tooltip['gen'] = 'Genitiv, Eigentümer wessen?';
// $tooltip['dat'] = 'Dativ, indirektes Objekt wem?';
// $tooltip['acc'] = 'Akkusativ, direktes Objekt wen?';
// $tooltip['abl'] = 'Ablativ, Herkunft woher?';
// $tooltip['ins'] = 'Instrumentiv, Mittel womit?';
// $tooltip['loc'] = 'Lokativ, Ort wo?';
// $tooltip['voc'] = 'Vokativ, Anrede wer?';
// $tooltip['norm'] = 'Normativ, Normalform';
// $tooltip['dimi'] = 'Diminutiv, Verkleinerungsform';
// $tooltip['augm'] = 'Augmentativ, Vergrößerungsform';
// $tooltip['inf'] = 'Infinitiv, Grundform';
// $tooltip['ifl'] = 'Inflektiv, Stammform';
// $tooltip['imp'] = 'Imperativ, Befehlsform';
// $tooltip['par'] = 'Partizip, Mittelwort';
// $tooltip['tra'] = 'Transgressiv, Nebenwort';
// $tooltip['aor'] = 'Aorist, abgeschlossene Vergangenheit';
// $tooltip['fut'] = 'Futurum, Zukunft';
// $tooltip['pres'] = 'Präsentum, Gegenwart';
// $tooltip['pret'] = 'Päteritum, Vergangenheit';
// $tooltip['conj'] = 'Konjunktiv, Möglichkeit';
// $tooltip['1.sg'] = '1. Person Singular, Sprecher Einzahl';
// $tooltip['2.sg'] = '2. Person Singular, Angesprochener Einzahl';
// $tooltip['3.sg'] = '3. Person Singular, Gesprächsgegenstand Einzahl';
// $tooltip['1.pl'] = '1. Person Plural, Sprecher Mehrzahl';
// $tooltip['2.pl'] = '2. Person Plural, Angesprochene Mehrzahl';
// $tooltip['3.pl'] = '3. Person Plural, Gesprächsgegenstände Mehrzahl';
// $tooltip['hon'] = 'Honorativ, Ehrenfürwort';
// $tooltip['hon.sg'] = 'Honorativ Singular, Ehrenfürwort Einzahl';
// $tooltip['hon.pl'] = 'Honorativ Plural, Ehrenfürwort Mehrzahl';
// $tooltip['impe'] = 'Imperfektiv, unvollendete Handlung';
// $tooltip['perf'] = 'Perfektiv, vollendete Handlung';
// $tooltip['flec'] = 'flektiv, regelwidrig gebeugt';
// $tooltip['infl'] = 'inflektiv, ungebeugt';
// $tooltip['di'] = 'direkt, unmittelbar';
// $tooltip['in'] = 'indirekt, mittelbar';
// $tooltip['sepa'] = 'separabel, trennbar';
// $tooltip['inse'] = 'inseparabel, untrennbar';
// $tooltip['acce'] = 'akzentual, betont';
// $tooltip['inac'] = 'inakzentual, unbetont';
// $tooltip['(in)'] = 'initial, am Satzanfang';
// $tooltip['(fi)'] = 'final, am Satzende';
// $tooltip['(av)'] = 'antivokalisch, vor Vokal';
// $tooltip['(ac)'] = 'antikonsonantisch, vor Konsonant';
// $tooltip['(pv)'] = 'postvokalisch, nach Vokal';
// $tooltip['(pc)'] = 'postkonsonantisch, nach Konsonant';

// Navigationsbox
$loc_portal = 'Portal';
$loc_suche = 'Sök';
$loc_downloads = 'Nedladdningar';
$loc_fragen = 'Frågor';
$loc_team = 'Lag';

// Impressumseite
$loc_impressum = 'Avtryck';
// $loc_gesetz = '';
// $loc_webseite = '';
// $loc_eigentuemer = '';
// $loc_autor = '';
// $loc_kontakt = '';
$loc_anschrift = 'Postadress';
$loc_deutschland = 'Tyskland';
$loc_eu = 'Europeiska Union';
// $loc_telefon = '';
// $loc_telefax = '';
// $loc_nachricht = '';
// $loc_adresse = '';
// $loc_spamblock = '';
// $loc_spamtext = '';
// $loc_absenden = '';
// $loc_loeschen = '';

// Dankseite
// $loc_danke = '';
// $loc_danke1 = '';
// $loc_danke2 = '';
// $loc_spende1 = '';
// $loc_spende2 = '';
// $loc_keine_adresse1 = '';
// $loc_keine_adresse2 = '';
// $loc_kein_inhalt1 = '';
// $loc_kein_inhalt2 = '';
// $loc_spam1 = '';
// $loc_spam2 = '';

// Portalseite
$loc_titel = 'Etymos-Ordbok';
// $loc_willkommen = '';
// $loc_wir_arbeiten = '';
// $loc_news = '';
// Sprachwahlfenster
// $loc_waehlen = '';
// $loc_aufschlagen = '';
// Informationsfenster
// $loc_information = '';
// $loc_info_pre = '';
// $loc_info_pre.= '';
// $loc_info_pre.= '';
// $loc_info_pre.= '';
// $loc_info_1 = '';
// $loc_info_2 = '';
// $loc_info_3 = '';
// $loc_info_4 = '';
// $loc_info_5 = '';
// $loc_info_6 = '';
// $loc_info_7 = '';
// $loc_info_8 = '';
// $loc_achtung1 = '';
// $loc_achtung1.= '';
// $loc_achtung1.= '';
// $loc_achtung2 = '';
// $loc_achtung2.= '';

// Suchseite
$loc_etymos = 'Etymos';
$loc_woerterbuch = 'Ordbok';
// Ergebnisfenster
// $loc_warning1 = '';
// $loc_warning2 = '';
// $loc_explanation1 = '';
// $loc_explanation2 = '';
// Zusatzfunktionsfenster
// $loc_collocation = '';
// $loc_definition = '';
// $loc_inflection = '';
// $loc_origin = '';
// $loc_family = '';
// $loc_keine_kollokation = '';
// $loc_keine_definition = '';
// $loc_keine_flexion = '';
// $loc_keine_herkunft = '';
// $loc_keine_familie = '';
// Wortsuchefenster
// $loc_wortsuche = '';
// $loc_suchen = '';
// Wortlistenfenster
// $loc_wortliste = '';
// $loc_kein_suchbegriff = '';
// Statusfenter
// $loc_status = '';
// $loc_bearbeitungsstufe = '';
// $loc_erklaerung = '';
// $loc_lemmata_in = '';
// $loc_artikel = '';
// $loc_level_name[1] = '';
// $loc_level_explain[1] = '';
// $loc_level_name[2] = '';
// $loc_level_explain[2] = '';
// $loc_level_name[3] = '';
// $loc_level_explain[3] = '';
// $loc_level_name[4] = '';
// $loc_level_explain[4] = '';
// $loc_level_name[5] = '';
// $loc_level_explain[5] = '';
// $loc_level_name[6] = '';
// $loc_level_explain[6] = '';
// $loc_level_name[7] = '';
// $loc_level_explain[7] = '';
// Materialfenter
// $loc_material = '';
// $loc_flex_para = '';
// $loc_einzelformen = '';

// Flexionsmodul
// $loc_fall_zahl = '';
// $loc_alle_genera = '';
// $loc_kein_schema = '';
// $loc_kein_paradigma = '';
// $loc_inflektierbar = '';
// $loc_siehe_einzelworte = '';
// $loc_anmerkung = '';
// $loc_genitivattribut_untypisch = '';

// Downloadseite
// $loc_noch_nicht = '';

// Fragenseite
// $loc_fragen_antworten = '';
// $loc_projekt = '';
// $loc_projekt_frage1 = '';
// $loc_projekt_antwort1 = '';
// $loc_projekt_antwort1.= '';
// $loc_projekt_antwort1.= '';
// $loc_projekt_antwort1.= '';
// $loc_projekt_frage2 = '';
// $loc_projekt_antwort2 = '';
// $loc_projekt_antwort2.= '';
// $loc_projekt_antwort2.= '';
// $loc_projekt_frage3 = '';
// $loc_projekt_antwort3a = '';
// $loc_projekt_antwort3b = '';
// $loc_projekt_antwort3c = '';
// $loc_projekt_antwort3d = '';
// $loc_projekt_antwort3e = '';
// $loc_projekt_antwort3f = '';
// $loc_projekt_antwort3g = '';
// $loc_projekt_antwort3g.= '';
// $loc_projekt_antwort3h = '';
// $loc_projekt_antwort3i = '';
// $loc_projekt_antwort3j = '';
// $loc_projekt_antwort3k = '';
// $loc_projekt_antwort3l = '';
// $loc_projekt_antwort3m = '';
// $loc_projekt_frage4 = '';
// $loc_projekt_antwort4 = '';
// $loc_projekt_antwort4.= '';
// $loc_projekt_frage5 = '';
// $loc_projekt_antwort5 = '';
// $loc_projekt_antwort5.= '';
// $loc_projekt_antwort5.= '';
// $loc_projekt_antwort5.= '';
// $loc_projekt_antwort5.= '';
// $loc_projekt_antwort5.= '';
// $loc_projekt_antwort5.= '';
// $loc_mitwirkung = '';
// $loc_mitwirkung_frage1 = '';
// $loc_mitwirkung_antwort1 = '';
// $loc_mitwirkung_antwort1.= '';
// $loc_mitwirkung_antwort1.= '';
// $loc_mitwirkung_antwort1.= '';
// $loc_mitwirkung_frage2 = '';
// $loc_mitwirkung_antwort2 = '';
// $loc_mitwirkung_antwort2.= '';
// $loc_mitwirkung_antwort2.= '';
// $loc_mitwirkung_frage3 = '';
// $loc_mitwirkung_antwort3a = '';
// $loc_mitwirkung_antwort3a.= '';
// $loc_mitwirkung_antwort3a.= '';
// $loc_mitwirkung_antwort3a.= '';
// $loc_mitwirkung_antwort3b = '';
// $loc_mitwirkung_antwort3b.= '';
// $loc_mitwirkung_antwort3b.= '';
// $loc_mitwirkung_antwort3b.= '';
// $loc_mitwirkung_frage4 = '';
// $loc_mitwirkung_antwort4 = '';
// $loc_mitwirkung_antwort4.= '';
// $loc_mitwirkung_antwort4.= '';
// $loc_mitwirkung_antwort4.= '';
// $loc_mitwirkung_frage5 = '';
// $loc_mitwirkung_antwort5 = '';
// $loc_button = '';
// $loc_button_quadrat = '';
// $loc_button_rund = '';
// $loc_button_weich = '';
// $loc_button_schirm = '';
// $loc_banner_klein = '';
// $loc_banner_normal = '';
// $loc_banner_gross = '';
// $loc_banner_riesig = '';
// $loc_banner_nichtoriginal = '';
// $loc_spenden = '';
// $loc_spenden_frage1 = '';
// $loc_spenden_antwort1 = '';
// $loc_spenden_antwort1.= '';
// $loc_spenden_trotzdem = '';
// $loc_spenden_trotzdem.= '';
// $loc_spenden_trotzdem.= '';
// $loc_spenden_betrag = '';
// $loc_jetzt_spenden = '';
// $loc_charakteristik = '';
// $loc_name = '';
// $loc_sprachen = '';
// $loc_sememe = '';
// $loc_bestaetigte_sememe = '';
// $loc_komplette_sememe = '';
// $loc_lemmata = '';
// $loc_kleinste_sprache = '';
// $loc_groesste_sprache = '';
// $loc_datenbank = '';
// $loc_programm = '';
// $loc_rubriken = '';

// Teamseite
// $loc_wir1 = '';
// $loc_wir2 = '';
// $loc_wir3 = '';
// $loc_wir4 = '';
// $loc_wir5 = '';
// $loc_verstaendnis1 = '';
// $loc_verstaendnis2 = '';
// $loc_verstaendnis3 = '';
// $loc_teamliste = '';
// $loc_projektleitung1 = '';
// $loc_projektleitung2 = '';
// $loc_redakteure1 = '';
// $loc_redakteure2 = '';
// $loc_redakteure3 = '';
// $loc_redakteure4 = '';
// $loc_redakteure5 = '';
// $loc_redakteure6 = '';
// $loc_redakteure7 = '';
// $loc_redakteure8 = '';
// $loc_programmierer1 = '';
// $loc_programmierer2 = '';
// $loc_tester1 = '';
// $loc_tester2 = '';
// $loc_ausschreibungen = '';
// $loc_bewerbungen1 = '';
// $loc_bewerbungen2 = '';
// $loc_bewerbungen3 = '';
// $loc_bewerbungen4 = '';
// $loc_bewerbungen5 = '';
// $loc_bewerbungen6 = '';
// $loc_bewerbungen7 = '';
// $loc_bewerbung_warnung1 = '';
// $loc_bewerbung_warnung2 = '';
// $loc_bewerbung_warnung3 = '';
// $loc_bewerbung_warnung4 = '';
// $loc_bewerbung_warnung5 = '';
// $loc_bewerbung_warnung6 = '';
// $loc_redaktion1 = '';
// $loc_redaktion2 = '';
// $loc_redaktion3 = '';
// $loc_redaktion4 = '';
// $loc_redaktion5 = '';
// $loc_redaktion6 = '';
// $loc_redaktion7 = '';
// $loc_redaktion8 = '';
// $loc_redaktion9 = '';
// $loc_redaktion10 = '';
// $loc_aussprache1 = '';
// $loc_aussprache2 = '';
// $loc_aussprache3 = '';
// $loc_aussprache4 = '';
// $loc_aussprache5 = '';
// $loc_entwicklung1 = '';
// $loc_entwicklung2 = '';
// $loc_entwicklung3 = '';
// $loc_entwicklung4 = '';
// $loc_kontaktformular = '';
// $loc_gibt_es_fragen = '';

// Logseite
// $loc_suchlog = '';
// $loc_letzte_suche = '';
// $loc_auflistung = '';
?>